version: '3.8'

services:
  dev-container:
    image: dev-env:latest
    container_name: dev-env
    volumes:
      - type: bind
        source: /Users/hshimizu/Documents/dev
        target: /mount
    stdin_open: true
    tty: true
